### ISSUE TITLE
lldb output is variable

### ISSUE THREAD

**Issue by mathieupoumeyrolsonos** [sonos/dinghy#158]
https://github.com/sonos/dinghy/blob/b822c749d68190d77f856784e7272992a10f149e/dinghy-lib/src/ios/device.rs#L772

sometimes there si one more line at the end. better look for the string "with status"

**Comment by simlay** [comment]
I noticed this behavior in #149. This is due to different versions of lldb/llvm I'm pretty sure. I couldn't find it in [the lldb release notes](https://releases.llvm.org/14.0.0/tools/lld/docs/ReleaseNotes.html) but generally adding a newline to a CLI output isn't considered "breaking". 

A long term solution might be to use something like the [lldb](https://github.com/endoli/lldb.rs) to make use of the actual C bindings to LLDB. That exact crate looks a bit nascent but it's worth thinking about.

**Comment by kali** [comment]
@simlay Yeah. that would be ideal. I tried it before, but lldb api was pretty bad... like a minefield of bugs as soon as you wander out of the "happy path", and what we are doing requires leaving that path a lot. That was years ago, it may be better now...
